### PR TITLE
Introduce PHP 8.1

### PR DESCRIPTION
**Pull request by gmorel**
> Error: During inheritance of IteratorAggregate: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: Return type of Alex\MailCatcher\Mime\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/vendor/alexandresalome/mailcatcher/Alex/MailCatcher/Mime/HeaderBag.php line 189 in /data/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90  
  Stack trace

Want to use this PR until merged

In your `composer.json`
Add an entry for this fork
```json
"repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:gmorel/mailcatcher.git"
        }
    ],
```
Then
`"alexandresalome/mailcatcher": "dev-feature/php8.1",`

Then `composer update alexandresalome/mailcatcher`

### CODE REVIEW

**Comment by gmorel** [comment]
Don't merge, your CI is broken

**Comment by mRoca** [comment]
Hi @alexandresalome & @gmorel , any news regarding this PR ?

**Comment by alexandresalome** [comment]
Sorry, I really miss time to check out things, so I'll just merge and tag, hoping it solves your needing.

**Comment by alexandresalome** [comment]
v1.4.0, done

**Comment by mRoca** [comment]
Everything seems to be working with 1.4.0 & PHP 8.1 ! Thank you very much @alexandresalome & @gmorel :-)

**Pull request merged**
