### PR TITLE
Update to behat 3

### PR DESCRIPTION
**Pull request by nucleartux**

### CODE REVIEW

**Comment by martinlindhe** [comment]
Any progress on this? I could take a look at fixing up the branch if you want.

**Comment by alexandresalome** [comment]
I still not needed it. If you manage to get things done, I'd be happy to merge it :)

**Comment by akovalyov** [comment]
@nucleartux could you reopen the PR?

**Comment by chtipepere** [comment]
Seems like everything's fine now :)

**Comment by akovalyov** [comment]
@chtipepere very cool!
@alexandresalome could you merge it?

**Pull request merged**
